### ISSUE TITLE
Create a seller-farmer form

### ISSUE THREAD

**Issue by MichaelKasingye** [BuildForSDGCohort2/Team-220-EnhancedFarmers-Frontend#20]
This form, the farmer will input details of the produce to sell. it will include:
-name of produce
- price of produce per quantity
-quantity in kgs(numbers input)
-Total amount selected 
-button to cart

**Comment by MUGABA** [comment]
Hey Mike it looks like your taling about an order form are you?

**Comment by MUGABA** [comment]
The perfect idea would be an order form that supports the customer to buy any product from the system we are yet to imprement it
