### ISSUE TITLE
create farmer profile form

### ISSUE THREAD

**Issue by MichaelKasingye** [BuildForSDGCohort2/Team-220-EnhancedFarmers-Frontend#29]
This form is one the investor or professional will see once the farmer has agreed to share their information with either of them. It will include fields:

Farmer Information:
*farmer name
*Farmer profile picture
*Farmer farming Experience(in years or months)
*Farmer size of land owned

Crop:
*Name of the crop
*Image of crop

Anticipated yield:
*in quantity
*in sales
*target market(whom are the farmers going to sale to).

Farmer farming Experience:(this is based on the period stated above)
*quantities sold
*sales in amount

AND a button to contact farmer email.

**Comment by MUGABA** [comment]
This issue was handled
